<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/impactos.php");
	include("$currDir/impactos_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('impactos');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "impactos";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`impactos`.`id`" => "id",
		"`impactos`.`puntaje`" => "puntaje",
		"`impactos`.`impactos`" => "impactos",
		"`impactos`.`imagen`" => "imagen"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`impactos`.`id`',
		2 => '`impactos`.`puntaje`',
		3 => 3,
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`impactos`.`id`" => "id",
		"`impactos`.`puntaje`" => "puntaje",
		"`impactos`.`impactos`" => "impactos",
		"`impactos`.`imagen`" => "imagen"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`impactos`.`id`" => "ID",
		"`impactos`.`puntaje`" => "Puntaje",
		"`impactos`.`impactos`" => "Impacto"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`impactos`.`id`" => "id",
		"`impactos`.`puntaje`" => "puntaje",
		"`impactos`.`impactos`" => "impactos"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`impactos` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "impactos_view.php";
	$x->RedirectAfterInsert = "index.php?#";
	$x->TableTitle = "Impactos";
	$x->TableIcon = "resources/table_icons/binary-thinking.png";
	$x->PrimaryKey = "`impactos`.`id`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Puntaje", "Impacto", "Imagen");
	$x->ColFieldName = array('puntaje', 'impactos', 'imagen');
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'templates/impactos_templateTV.html';
	$x->SelectedTemplate = 'templates/impactos_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `impactos`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='impactos' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `impactos`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='impactos' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`impactos`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: impactos_init
	$render=TRUE;
	if(function_exists('impactos_init')){
		$args=array();
		$render=impactos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `impactos`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery="select sum(`impactos`.`puntaje`) from ".$x->QueryFrom.' '.$QueryWhere;
		$res=sql($sumQuery, $eo);
		if($row=db_fetch_row($res)){
			$sumRow ="<tr class=\"success\">";
			if(!isset($_REQUEST['Print_x'])) $sumRow.="<td class=\"text-center\"><strong>&sum;</strong></td>";
			$sumRow.="<td class=\"text-right\">{$row[0]}</td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="</tr>";

			$x->HTML=str_replace("<!-- tv data below -->", '', $x->HTML);
			$x->HTML=str_replace("<!-- tv data above -->", $sumRow, $x->HTML);
		}
	}

	// hook: impactos_header
	$headerCode='';
	if(function_exists('impactos_header')){
		$args=array();
		$headerCode=impactos_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: impactos_footer
	$footerCode='';
	if(function_exists('impactos_footer')){
		$args=array();
		$footerCode=impactos_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>