<?php

// Data functions (insert, update, delete, form) for table persona

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function persona_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('persona');
	if(!$arrPerm[1]){
		return false;
	}

	$data['usuario'] = makeSafe($_REQUEST['usuario']);
		if($data['usuario'] == empty_lookup_value){ $data['usuario'] = ''; }
	$data['nombre'] = makeSafe($_REQUEST['nombre']);
		if($data['nombre'] == empty_lookup_value){ $data['nombre'] = ''; }
	$data['apellido'] = makeSafe($_REQUEST['apellido']);
		if($data['apellido'] == empty_lookup_value){ $data['apellido'] = ''; }
	$data['correo'] = makeSafe($_REQUEST['correo']);
		if($data['correo'] == empty_lookup_value){ $data['correo'] = ''; }
	$data['celular'] = makeSafe($_REQUEST['celular']);
		if($data['celular'] == empty_lookup_value){ $data['celular'] = ''; }
	$data['cumpleanos'] = intval($_REQUEST['cumpleanosYear']) . '-' . intval($_REQUEST['cumpleanosMonth']) . '-' . intval($_REQUEST['cumpleanosDay']);
	$data['cumpleanos'] = parseMySQLDate($data['cumpleanos'], '');
	if($data['usuario']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Usuario': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['nombre']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Nombre': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['apellido']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Apellido': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['correo']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Correo': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['celular']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Celular': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['cumpleanos']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Cumplea&#241;os': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: persona_before_insert
	if(function_exists('persona_before_insert')){
		$args=array();
		if(!persona_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `persona` set       `usuario`=' . (($data['usuario'] !== '' && $data['usuario'] !== NULL) ? "'{$data['usuario']}'" : 'NULL') . ', `nombre`=' . (($data['nombre'] !== '' && $data['nombre'] !== NULL) ? "'{$data['nombre']}'" : 'NULL') . ', `apellido`=' . (($data['apellido'] !== '' && $data['apellido'] !== NULL) ? "'{$data['apellido']}'" : 'NULL') . ', `correo`=' . (($data['correo'] !== '' && $data['correo'] !== NULL) ? "'{$data['correo']}'" : 'NULL') . ', `celular`=' . (($data['celular'] !== '' && $data['celular'] !== NULL) ? "'{$data['celular']}'" : 'NULL') . ', `cumpleanos`=' . (($data['cumpleanos'] !== '' && $data['cumpleanos'] !== NULL) ? "'{$data['cumpleanos']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"persona_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: persona_after_insert
	if(function_exists('persona_after_insert')){
		$res = sql("select * from `persona` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!persona_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='persona', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function persona_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('persona');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='persona' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='persona' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: persona_before_delete
	if(function_exists('persona_before_delete')){
		$args=array();
		if(!persona_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: puntos
	$res = sql("select `id` from `persona` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `puntos` where `postulante`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "puntos", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "puntos", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='persona_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='persona_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: puntos
	$res = sql("select `id` from `persona` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `puntos` where `persona`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "puntos", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "puntos", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='persona_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='persona_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `persona` where `id`='$selected_id'", $eo);

	// hook: persona_after_delete
	if(function_exists('persona_after_delete')){
		$args=array();
		persona_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='persona' and pkValue='$selected_id'", $eo);
}

function persona_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('persona');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='persona' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='persona' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['usuario'] = makeSafe($_REQUEST['usuario']);
		if($data['usuario'] == empty_lookup_value){ $data['usuario'] = ''; }
	if($data['usuario']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Usuario': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['nombre'] = makeSafe($_REQUEST['nombre']);
		if($data['nombre'] == empty_lookup_value){ $data['nombre'] = ''; }
	if($data['nombre']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['apellido'] = makeSafe($_REQUEST['apellido']);
		if($data['apellido'] == empty_lookup_value){ $data['apellido'] = ''; }
	if($data['apellido']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Apellido': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['correo'] = makeSafe($_REQUEST['correo']);
		if($data['correo'] == empty_lookup_value){ $data['correo'] = ''; }
	if($data['correo']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Correo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['celular'] = makeSafe($_REQUEST['celular']);
		if($data['celular'] == empty_lookup_value){ $data['celular'] = ''; }
	if($data['celular']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Celular': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['cumpleanos'] = intval($_REQUEST['cumpleanosYear']) . '-' . intval($_REQUEST['cumpleanosMonth']) . '-' . intval($_REQUEST['cumpleanosDay']);
	$data['cumpleanos'] = parseMySQLDate($data['cumpleanos'], '');
	if($data['cumpleanos']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cumplea&#241;os': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: persona_before_update
	if(function_exists('persona_before_update')){
		$args=array();
		if(!persona_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `persona` set       `usuario`=' . (($data['usuario'] !== '' && $data['usuario'] !== NULL) ? "'{$data['usuario']}'" : 'NULL') . ', `nombre`=' . (($data['nombre'] !== '' && $data['nombre'] !== NULL) ? "'{$data['nombre']}'" : 'NULL') . ', `apellido`=' . (($data['apellido'] !== '' && $data['apellido'] !== NULL) ? "'{$data['apellido']}'" : 'NULL') . ', `correo`=' . (($data['correo'] !== '' && $data['correo'] !== NULL) ? "'{$data['correo']}'" : 'NULL') . ', `celular`=' . (($data['celular'] !== '' && $data['celular'] !== NULL) ? "'{$data['celular']}'" : 'NULL') . ', `cumpleanos`=' . (($data['cumpleanos'] !== '' && $data['cumpleanos'] !== NULL) ? "'{$data['cumpleanos']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="persona_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: persona_after_update
	if(function_exists('persona_after_update')){
		$res = sql("SELECT * FROM `persona` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!persona_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='persona' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function persona_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('persona');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: cumpleanos
	$combo_cumpleanos = new DateCombo;
	$combo_cumpleanos->DateFormat = "mdy";
	$combo_cumpleanos->MinYear = 1900;
	$combo_cumpleanos->MaxYear = 2100;
	$combo_cumpleanos->DefaultDate = parseMySQLDate('', '');
	$combo_cumpleanos->MonthNames = $Translation['month names'];
	$combo_cumpleanos->NamePrefix = 'cumpleanos';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='persona' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='persona' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `persona` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_cumpleanos->DefaultDate = $row['cumpleanos'];
	}else{
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/persona_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/persona_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Persona details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return persona_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return persona_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return persona_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#usuario').replaceWith('<div class=\"form-control-static\" id=\"usuario\">' + (jQuery('#usuario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nombre').replaceWith('<div class=\"form-control-static\" id=\"nombre\">' + (jQuery('#nombre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#apellido').replaceWith('<div class=\"form-control-static\" id=\"apellido\">' + (jQuery('#apellido').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#correo').replaceWith('<div class=\"form-control-static\" id=\"correo\">' + (jQuery('#correo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#celular').replaceWith('<div class=\"form-control-static\" id=\"celular\">' + (jQuery('#celular').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#cumpleanos').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#cumpleanosDay, #cumpleanosMonth, #cumpleanosYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(cumpleanos)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_cumpleanos->GetHTML(true) . '</div>' : $combo_cumpleanos->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(cumpleanos)%%>', $combo_cumpleanos->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(usuario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(nombre)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(apellido)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(correo)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(celular)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(cumpleanos)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(usuario)%%>', html_attr($row['usuario']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(usuario)%%>', urlencode($urow['usuario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(nombre)%%>', html_attr($row['nombre']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(nombre)%%>', urlencode($urow['nombre']), $templateCode);
		$templateCode=str_replace('<%%VALUE(apellido)%%>', html_attr($row['apellido']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(apellido)%%>', urlencode($urow['apellido']), $templateCode);
		$templateCode=str_replace('<%%VALUE(correo)%%>', html_attr($row['correo']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(correo)%%>', urlencode($urow['correo']), $templateCode);
		$templateCode=str_replace('<%%VALUE(celular)%%>', html_attr($row['celular']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(celular)%%>', urlencode($urow['celular']), $templateCode);
		$templateCode=str_replace('<%%VALUE(cumpleanos)%%>', @date('m/d/Y', @strtotime(html_attr($row['cumpleanos']))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(cumpleanos)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['cumpleanos'])))), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(usuario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(usuario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(nombre)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(nombre)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(apellido)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(apellido)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(correo)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(correo)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(celular)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(celular)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(cumpleanos)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(cumpleanos)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: persona_dv
	if(function_exists('persona_dv')){
		$args=array();
		persona_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>