<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/persona.php");
	include("$currDir/persona_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('persona');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "persona";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`persona`.`id`" => "id",
		"`persona`.`usuario`" => "usuario",
		"`persona`.`nombre`" => "nombre",
		"`persona`.`apellido`" => "apellido",
		"`persona`.`correo`" => "correo",
		"`persona`.`celular`" => "celular",
		"if(`persona`.`cumpleanos`,date_format(`persona`.`cumpleanos`,'%m/%d/%Y'),'')" => "cumpleanos"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`persona`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`persona`.`cumpleanos`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`persona`.`id`" => "id",
		"`persona`.`usuario`" => "usuario",
		"`persona`.`nombre`" => "nombre",
		"`persona`.`apellido`" => "apellido",
		"`persona`.`correo`" => "correo",
		"`persona`.`celular`" => "celular",
		"if(`persona`.`cumpleanos`,date_format(`persona`.`cumpleanos`,'%m/%d/%Y'),'')" => "cumpleanos"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`persona`.`id`" => "ID",
		"`persona`.`usuario`" => "Usuario",
		"`persona`.`nombre`" => "Nombre",
		"`persona`.`apellido`" => "Apellido",
		"`persona`.`correo`" => "Correo",
		"`persona`.`celular`" => "Celular",
		"`persona`.`cumpleanos`" => "Cumplea&#241;os"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`persona`.`id`" => "id",
		"`persona`.`usuario`" => "usuario",
		"`persona`.`nombre`" => "nombre",
		"`persona`.`apellido`" => "apellido",
		"`persona`.`correo`" => "correo",
		"`persona`.`celular`" => "celular",
		"if(`persona`.`cumpleanos`,date_format(`persona`.`cumpleanos`,'%m/%d/%Y'),'')" => "cumpleanos"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`persona` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "persona_view.php";
	$x->RedirectAfterInsert = "persona_view.php?SelectedID=#ID#";
	$x->TableTitle = "Persona";
	$x->TableIcon = "resources/table_icons/business-male-team.png";
	$x->PrimaryKey = "`persona`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Usuario", "Nombre", "Apellido", "Correo", "Celular", "Cumplea&#241;os");
	$x->ColFieldName = array('usuario', 'nombre', 'apellido', 'correo', 'celular', 'cumpleanos');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	$x->Template = 'templates/persona_templateTV.html';
	$x->SelectedTemplate = 'templates/persona_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `persona`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='persona' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `persona`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='persona' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`persona`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: persona_init
	$render=TRUE;
	if(function_exists('persona_init')){
		$args=array();
		$render=persona_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: persona_header
	$headerCode='';
	if(function_exists('persona_header')){
		$args=array();
		$headerCode=persona_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: persona_footer
	$footerCode='';
	if(function_exists('persona_footer')){
		$args=array();
		$footerCode=persona_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>