<?php

// Data functions (insert, update, delete, form) for table puntos

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function puntos_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('puntos');
	if(!$arrPerm[1]){
		return false;
	}

	$data['fecha_actividad'] = intval($_REQUEST['fecha_actividadYear']) . '-' . intval($_REQUEST['fecha_actividadMonth']) . '-' . intval($_REQUEST['fecha_actividadDay']);
	$data['fecha_actividad'] = parseMySQLDate($data['fecha_actividad'], '');
	$data['fecha_ingreso'] = parseCode('<%%creationDateTime%%>', true);
	$data['motivo'] = br2nl(makeSafe($_REQUEST['motivo']));
	$data['puntaje'] = makeSafe($_REQUEST['puntaje']);
		if($data['puntaje'] == empty_lookup_value){ $data['puntaje'] = ''; }
	$data['impacto'] = makeSafe($_REQUEST['impacto']);
		if($data['impacto'] == empty_lookup_value){ $data['impacto'] = ''; }
	$data['emblema'] = makeSafe($_REQUEST['impacto']);
		if($data['emblema'] == empty_lookup_value){ $data['emblema'] = ''; }
	$data['postulante'] = makeSafe($_REQUEST['postulante']);
		if($data['postulante'] == empty_lookup_value){ $data['postulante'] = ''; }
	$data['persona'] = makeSafe($_REQUEST['persona']);
		if($data['persona'] == empty_lookup_value){ $data['persona'] = ''; }
	if($data['fecha_actividad']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Fecha de la Actividad': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['motivo']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Motivo': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['puntaje']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Puntaje': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['impacto']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Impacto': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['postulante']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Postulante': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['persona']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Ganador': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: puntos_before_insert
	if(function_exists('puntos_before_insert')){
		$args=array();
		if(!puntos_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `puntos` set       `fecha_actividad`=' . (($data['fecha_actividad'] !== '' && $data['fecha_actividad'] !== NULL) ? "'{$data['fecha_actividad']}'" : 'NULL') . ', `fecha_ingreso`=' . "'{$data['fecha_ingreso']}'" . ', `motivo`=' . (($data['motivo'] !== '' && $data['motivo'] !== NULL) ? "'{$data['motivo']}'" : 'NULL') . ', `puntaje`=' . (($data['puntaje'] !== '' && $data['puntaje'] !== NULL) ? "'{$data['puntaje']}'" : 'NULL') . ', `impacto`=' . (($data['impacto'] !== '' && $data['impacto'] !== NULL) ? "'{$data['impacto']}'" : 'NULL') . ', `emblema`=' . (($data['emblema'] !== '' && $data['emblema'] !== NULL) ? "'{$data['emblema']}'" : 'NULL') . ', `postulante`=' . (($data['postulante'] !== '' && $data['postulante'] !== NULL) ? "'{$data['postulante']}'" : 'NULL') . ', `persona`=' . (($data['persona'] !== '' && $data['persona'] !== NULL) ? "'{$data['persona']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"puntos_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: puntos_after_insert
	if(function_exists('puntos_after_insert')){
		$res = sql("select * from `puntos` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!puntos_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='puntos', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function puntos_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('puntos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='puntos' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='puntos' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: puntos_before_delete
	if(function_exists('puntos_before_delete')){
		$args=array();
		if(!puntos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `puntos` where `id`='$selected_id'", $eo);

	// hook: puntos_after_delete
	if(function_exists('puntos_after_delete')){
		$args=array();
		puntos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='puntos' and pkValue='$selected_id'", $eo);
}

function puntos_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('puntos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='puntos' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='puntos' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['fecha_actividad'] = intval($_REQUEST['fecha_actividadYear']) . '-' . intval($_REQUEST['fecha_actividadMonth']) . '-' . intval($_REQUEST['fecha_actividadDay']);
	$data['fecha_actividad'] = parseMySQLDate($data['fecha_actividad'], '');
	if($data['fecha_actividad']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fecha de la Actividad': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['motivo'] = br2nl(makeSafe($_REQUEST['motivo']));
	if($data['motivo']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Motivo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['puntaje'] = makeSafe($_REQUEST['puntaje']);
		if($data['puntaje'] == empty_lookup_value){ $data['puntaje'] = ''; }
	if($data['puntaje']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Puntaje': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['impacto'] = makeSafe($_REQUEST['impacto']);
		if($data['impacto'] == empty_lookup_value){ $data['impacto'] = ''; }
	if($data['impacto']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Impacto': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['emblema'] = makeSafe($_REQUEST['impacto']);
		if($data['emblema'] == empty_lookup_value){ $data['emblema'] = ''; }
	$data['postulante'] = makeSafe($_REQUEST['postulante']);
		if($data['postulante'] == empty_lookup_value){ $data['postulante'] = ''; }
	if($data['postulante']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Postulante': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['persona'] = makeSafe($_REQUEST['persona']);
		if($data['persona'] == empty_lookup_value){ $data['persona'] = ''; }
	if($data['persona']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Ganador': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: puntos_before_update
	if(function_exists('puntos_before_update')){
		$args=array();
		if(!puntos_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `puntos` set       `fecha_actividad`=' . (($data['fecha_actividad'] !== '' && $data['fecha_actividad'] !== NULL) ? "'{$data['fecha_actividad']}'" : 'NULL') . ', `fecha_ingreso`=`fecha_ingreso`' . ', `motivo`=' . (($data['motivo'] !== '' && $data['motivo'] !== NULL) ? "'{$data['motivo']}'" : 'NULL') . ', `puntaje`=' . (($data['puntaje'] !== '' && $data['puntaje'] !== NULL) ? "'{$data['puntaje']}'" : 'NULL') . ', `impacto`=' . (($data['impacto'] !== '' && $data['impacto'] !== NULL) ? "'{$data['impacto']}'" : 'NULL') . ', `emblema`=' . (($data['emblema'] !== '' && $data['emblema'] !== NULL) ? "'{$data['emblema']}'" : 'NULL') . ', `postulante`=' . (($data['postulante'] !== '' && $data['postulante'] !== NULL) ? "'{$data['postulante']}'" : 'NULL') . ', `persona`=' . (($data['persona'] !== '' && $data['persona'] !== NULL) ? "'{$data['persona']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="puntos_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: puntos_after_update
	if(function_exists('puntos_after_update')){
		$res = sql("SELECT * FROM `puntos` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!puntos_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='puntos' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function puntos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('puntos');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_impacto = thisOr(undo_magic_quotes($_REQUEST['filterer_impacto']), '');
	$filterer_postulante = thisOr(undo_magic_quotes($_REQUEST['filterer_postulante']), '');
	$filterer_persona = thisOr(undo_magic_quotes($_REQUEST['filterer_persona']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: fecha_actividad
	$combo_fecha_actividad = new DateCombo;
	$combo_fecha_actividad->DateFormat = "mdy";
	$combo_fecha_actividad->MinYear = 2017;
	$combo_fecha_actividad->MaxYear = 2100;
	$combo_fecha_actividad->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_actividad->MonthNames = $Translation['month names'];
	$combo_fecha_actividad->NamePrefix = 'fecha_actividad';
	// combobox: puntaje
	$combo_puntaje = new Combo;
	$combo_puntaje->ListType = 0;
	$combo_puntaje->MultipleSeparator = ', ';
	$combo_puntaje->ListBoxHeight = 10;
	$combo_puntaje->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/puntos.puntaje.csv')){
		$puntaje_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/puntos.puntaje.csv')));
		$combo_puntaje->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($puntaje_data)));
		$combo_puntaje->ListData = $combo_puntaje->ListItem;
	}else{
		$combo_puntaje->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("-45;;45;;180;;400")));
		$combo_puntaje->ListData = $combo_puntaje->ListItem;
	}
	$combo_puntaje->SelectName = 'puntaje';
	$combo_puntaje->AllowNull = false;
	// combobox: impacto
	$combo_impacto = new DataCombo;
	// combobox: postulante
	$combo_postulante = new DataCombo;
	// combobox: persona
	$combo_persona = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='puntos' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='puntos' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `puntos` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_fecha_actividad->DefaultDate = $row['fecha_actividad'];
		$combo_puntaje->SelectedData = $row['puntaje'];
		$combo_impacto->SelectedData = $row['impacto'];
		$combo_postulante->SelectedData = $row['postulante'];
		$combo_persona->SelectedData = $row['persona'];
	}else{
		$combo_puntaje->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_impacto->SelectedData = $filterer_impacto;
		$combo_postulante->SelectedData = $filterer_postulante;
		$combo_persona->SelectedData = $filterer_persona;
	}
	$combo_puntaje->Render();
	$combo_impacto->HTML = '<span id="impacto-container' . $rnd1 . '"></span><input type="hidden" name="impacto" id="impacto' . $rnd1 . '" value="' . html_attr($combo_impacto->SelectedData) . '">';
	$combo_impacto->MatchText = '<span id="impacto-container-readonly' . $rnd1 . '"></span><input type="hidden" name="impacto" id="impacto' . $rnd1 . '" value="' . html_attr($combo_impacto->SelectedData) . '">';
	$combo_postulante->HTML = '<span id="postulante-container' . $rnd1 . '"></span><input type="hidden" name="postulante" id="postulante' . $rnd1 . '" value="' . html_attr($combo_postulante->SelectedData) . '">';
	$combo_postulante->MatchText = '<span id="postulante-container-readonly' . $rnd1 . '"></span><input type="hidden" name="postulante" id="postulante' . $rnd1 . '" value="' . html_attr($combo_postulante->SelectedData) . '">';
	$combo_persona->HTML = '<span id="persona-container' . $rnd1 . '"></span><input type="hidden" name="persona" id="persona' . $rnd1 . '" value="' . html_attr($combo_persona->SelectedData) . '">';
	$combo_persona->MatchText = '<span id="persona-container-readonly' . $rnd1 . '"></span><input type="hidden" name="persona" id="persona' . $rnd1 . '" value="' . html_attr($combo_persona->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_impacto__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['impacto'] : $filterer_impacto); ?>"};
		var current_postulante__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['postulante'] : $filterer_postulante); ?>"};
		var current_persona__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['persona'] : $filterer_persona); ?>"};

		jQuery(function() {
			if(typeof(impacto_reload__RAND__) == 'function') impacto_reload__RAND__();
			if(typeof(postulante_reload__RAND__) == 'function') postulante_reload__RAND__();
			if(typeof(persona_reload__RAND__) == 'function') persona_reload__RAND__();
		});
		function impacto_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#impacto-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_impacto__RAND__.value, t: 'puntos', f: 'impacto' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						$j('[name="impacto"]').val(resp.results[0].id);
						$j('[id=impacto-container-readonly__RAND__]').html('<span id="impacto-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=impactos_view_parent]').hide(); }else{ $j('.btn[id=impactos_view_parent]').show(); }


						if(typeof(impacto_update_autofills__RAND__) == 'function') impacto_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'puntos', f: 'impacto' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_impacto__RAND__.value = e.added.id;
				current_impacto__RAND__.text = e.added.text;
				$j('[name="impacto"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=impactos_view_parent]').hide(); }else{ $j('.btn[id=impactos_view_parent]').show(); }


				if(typeof(impacto_update_autofills__RAND__) == 'function') impacto_update_autofills__RAND__();
			});

			if(!$j("#impacto-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_impacto__RAND__.value, t: 'puntos', f: 'impacto' }
				}).done(function(resp){
					$j('[name="impacto"]').val(resp.results[0].id);
					$j('[id=impacto-container-readonly__RAND__]').html('<span id="impacto-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=impactos_view_parent]').hide(); }else{ $j('.btn[id=impactos_view_parent]').show(); }

					if(typeof(impacto_update_autofills__RAND__) == 'function') impacto_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_impacto__RAND__.value, t: 'puntos', f: 'impacto' }
			}).done(function(resp){
				$j('[id=impacto-container__RAND__], [id=impacto-container-readonly__RAND__]').html('<span id="impacto-match-text">' + resp.results[0].text + '</span>');
				if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=impactos_view_parent]').hide(); }else{ $j('.btn[id=impactos_view_parent]').show(); }

				if(typeof(impacto_update_autofills__RAND__) == 'function') impacto_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function postulante_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#postulante-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_postulante__RAND__.value, t: 'puntos', f: 'postulante' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						$j('[name="postulante"]').val(resp.results[0].id);
						$j('[id=postulante-container-readonly__RAND__]').html('<span id="postulante-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }


						if(typeof(postulante_update_autofills__RAND__) == 'function') postulante_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'puntos', f: 'postulante' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_postulante__RAND__.value = e.added.id;
				current_postulante__RAND__.text = e.added.text;
				$j('[name="postulante"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }


				if(typeof(postulante_update_autofills__RAND__) == 'function') postulante_update_autofills__RAND__();
			});

			if(!$j("#postulante-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_postulante__RAND__.value, t: 'puntos', f: 'postulante' }
				}).done(function(resp){
					$j('[name="postulante"]').val(resp.results[0].id);
					$j('[id=postulante-container-readonly__RAND__]').html('<span id="postulante-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }

					if(typeof(postulante_update_autofills__RAND__) == 'function') postulante_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_postulante__RAND__.value, t: 'puntos', f: 'postulante' }
			}).done(function(resp){
				$j('[id=postulante-container__RAND__], [id=postulante-container-readonly__RAND__]').html('<span id="postulante-match-text">' + resp.results[0].text + '</span>');
				if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }

				if(typeof(postulante_update_autofills__RAND__) == 'function') postulante_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function persona_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#persona-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_persona__RAND__.value, t: 'puntos', f: 'persona' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						$j('[name="persona"]').val(resp.results[0].id);
						$j('[id=persona-container-readonly__RAND__]').html('<span id="persona-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }


						if(typeof(persona_update_autofills__RAND__) == 'function') persona_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'puntos', f: 'persona' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_persona__RAND__.value = e.added.id;
				current_persona__RAND__.text = e.added.text;
				$j('[name="persona"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }


				if(typeof(persona_update_autofills__RAND__) == 'function') persona_update_autofills__RAND__();
			});

			if(!$j("#persona-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_persona__RAND__.value, t: 'puntos', f: 'persona' }
				}).done(function(resp){
					$j('[name="persona"]').val(resp.results[0].id);
					$j('[id=persona-container-readonly__RAND__]').html('<span id="persona-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }

					if(typeof(persona_update_autofills__RAND__) == 'function') persona_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_persona__RAND__.value, t: 'puntos', f: 'persona' }
			}).done(function(resp){
				$j('[id=persona-container__RAND__], [id=persona-container-readonly__RAND__]').html('<span id="persona-match-text">' + resp.results[0].text + '</span>');
				if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=persona_view_parent]').hide(); }else{ $j('.btn[id=persona_view_parent]').show(); }

				if(typeof(persona_update_autofills__RAND__) == 'function') persona_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/puntos_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/puntos_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle de los Puntos', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return puntos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return puntos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return puntos_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#fecha_actividad').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fecha_actividadDay, #fecha_actividadMonth, #fecha_actividadYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#motivo').replaceWith('<div class=\"form-control-static\" id=\"motivo\">' + (jQuery('#motivo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#puntaje').replaceWith('<div class=\"form-control-static\" id=\"puntaje\">' + (jQuery('#puntaje').val() || '') + '</div>'); jQuery('#puntaje-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#impacto').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#impacto_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#postulante').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#postulante_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#persona').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#persona_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(fecha_actividad)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fecha_actividad->GetHTML(true) . '</div>' : $combo_fecha_actividad->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(fecha_actividad)%%>', $combo_fecha_actividad->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(puntaje)%%>', $combo_puntaje->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(puntaje)%%>', $combo_puntaje->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(impacto)%%>', $combo_impacto->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(impacto)%%>', $combo_impacto->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(impacto)%%>', urlencode($combo_impacto->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(postulante)%%>', $combo_postulante->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(postulante)%%>', $combo_postulante->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(postulante)%%>', urlencode($combo_postulante->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(persona)%%>', $combo_persona->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(persona)%%>', $combo_persona->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(persona)%%>', urlencode($combo_persona->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'impacto' => array('impactos', 'Impacto'), 'postulante' => array('persona', 'Postulante'), 'persona' => array('persona', 'Ganador'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(fecha_actividad)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(fecha_ingreso)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(motivo)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(puntaje)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(impacto)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(postulante)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(persona)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(fecha_actividad)%%>', @date('m/d/Y', @strtotime(html_attr($row['fecha_actividad']))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fecha_actividad)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['fecha_actividad'])))), $templateCode);
		$templateCode=str_replace('<%%VALUE(fecha_ingreso)%%>', html_attr($row['fecha_ingreso']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fecha_ingreso)%%>', urlencode($urow['fecha_ingreso']), $templateCode);
		if($dvprint){
			$templateCode = str_replace('<%%VALUE(motivo)%%>', nl2br(html_attr($row['motivo'])), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(motivo)%%>', html_attr($row['motivo']), $templateCode);
		}
		$templateCode=str_replace('<%%URLVALUE(motivo)%%>', urlencode($urow['motivo']), $templateCode);
		$templateCode=str_replace('<%%VALUE(puntaje)%%>', html_attr($row['puntaje']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(puntaje)%%>', urlencode($urow['puntaje']), $templateCode);
		$templateCode=str_replace('<%%VALUE(impacto)%%>', html_attr($row['impacto']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(impacto)%%>', urlencode($urow['impacto']), $templateCode);
		$templateCode=str_replace('<%%VALUE(postulante)%%>', html_attr($row['postulante']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(postulante)%%>', urlencode($urow['postulante']), $templateCode);
		$templateCode=str_replace('<%%VALUE(persona)%%>', html_attr($row['persona']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(persona)%%>', urlencode($urow['persona']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(fecha_actividad)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fecha_actividad)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(fecha_ingreso)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fecha_ingreso)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(motivo)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(motivo)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(puntaje)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(puntaje)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(impacto)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(impacto)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(postulante)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(postulante)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(persona)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(persona)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode.="\timpacto_update_autofills$rnd1 = function(){\n";
	$templateCode.="\t\tnew Ajax.Request(\n";
	if($dvprint){
		$templateCode.="\t\t\t'puntos_autofill.php?rnd1=$rnd1&mfk=impacto&id=' + encodeURIComponent('".addslashes($row['impacto'])."'),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get'}\n";
	}else{
		$templateCode.="\t\t\t'puntos_autofill.php?rnd1=$rnd1&mfk=impacto&id=' + encodeURIComponent(current_impacto{$rnd1}.value),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get', onCreate: function(){ \$j('#impacto$rnd1').prop('disabled', true); \$j('#impactoLoading').html('<img src=loading.gif align=top>'); }, onComplete: function(){".(($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#impacto$rnd1').prop('disabled', false); " : "\$j('#impacto$rnd1').prop('disabled', true); ")."\$j('#impactoLoading').html('');}}\n";
	}
	$templateCode.="\t\t);\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$j('#impacto_caption').length) \$j('#impacto_caption').click(function(){ impacto_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: puntos_dv
	if(function_exists('puntos_dv')){
		$args=array();
		puntos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>