<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/reglamento.php");
	include("$currDir/reglamento_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('reglamento');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "reglamento";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`reglamento`.`id`" => "id",
		"`reglamento`.`archivo`" => "archivo",
		"`reglamento`.`descripcion`" => "descripcion"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`reglamento`.`id`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`reglamento`.`id`" => "id",
		"`reglamento`.`archivo`" => "archivo",
		"`reglamento`.`descripcion`" => "descripcion"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`reglamento`.`id`" => "ID",
		"`reglamento`.`archivo`" => "Archivo",
		"`reglamento`.`descripcion`" => "Descripcion"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`reglamento`.`id`" => "id",
		"`reglamento`.`archivo`" => "archivo",
		"`reglamento`.`descripcion`" => "descripcion"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`reglamento` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 0;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 0;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "reglamento_view.php";
	$x->RedirectAfterInsert = "index.php?#";
	$x->TableTitle = "Lineamientos del Bushido";
	$x->TableIcon = "resources/table_icons/apple-icon-72x72.png";
	$x->PrimaryKey = "`reglamento`.`id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Archivo", "Descripcion");
	$x->ColFieldName = array('archivo', 'descripcion');
	$x->ColNumber  = array(2, 3);

	$x->Template = 'templates/reglamento_templateTV.html';
	$x->SelectedTemplate = 'templates/reglamento_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `reglamento`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='reglamento' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `reglamento`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='reglamento' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`reglamento`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: reglamento_init
	$render=TRUE;
	if(function_exists('reglamento_init')){
		$args=array();
		$render=reglamento_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: reglamento_header
	$headerCode='';
	if(function_exists('reglamento_header')){
		$args=array();
		$headerCode=reglamento_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: reglamento_footer
	$footerCode='';
	if(function_exists('reglamento_footer')){
		$args=array();
		$footerCode=reglamento_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>